"""
INDEX.yaml builder.

Walks `openspec/specs/` for `*.spec.md`, parses each, and emits a
deterministic YAML index per the schema in INDEX.yaml's header.

Per [`ADR-0004` §6](../../openspec/architecture/decisions/ADR-0004-spec-storage-discipline.md),
INDEX.yaml is the "sole retrieval surface for tooling".

`check_index` compares the on-disk INDEX.yaml against what
`build_index_data` would produce, ignoring the `generated_at`
timestamp. Returns 0 when up-to-date, 1 when stale, 2 when the target
is missing or unparseable.
"""

from __future__ import annotations

import datetime as _dt
import pathlib

import yaml

from .parser import parse_spec_file


_SCHEMA_VERSION = 1


def _entry_for_req(req, repo_root: pathlib.Path) -> dict:
    fm = req.frontmatter or {}
    return {
        "id": req.heading_id,
        "file": pathlib.Path(req.file).resolve().relative_to(repo_root).as_posix(),
        "revision": fm.get("revision"),
        "status": fm.get("status"),
        "tier": fm.get("tier"),
        "phase": fm.get("phase"),
        "supersedes": fm.get("supersedes"),
        "superseded_by": fm.get("superseded_by"),
    }


def build_index_data(
    specs_root: pathlib.Path,
    repo_root: pathlib.Path,
) -> dict:
    requirements: list[dict] = []
    for path in sorted(specs_root.rglob("*.spec.md")):
        spec = parse_spec_file(path)
        for req in spec.requirements:
            if req.frontmatter is None:
                # Malformed REQ blocks aren't indexable; spec-frontmatter-valid
                # already flags them through `validate`.
                continue
            requirements.append(_entry_for_req(req, repo_root))

    requirements.sort(key=lambda e: e["id"])

    return {
        "version": _SCHEMA_VERSION,
        "generated_at": _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "requirements": requirements,
    }


def _serialize(data: dict) -> str:
    # Preserve the header comment by emitting it; spec_lint owns the file.
    header = (
        "---\n"
        "# Auto-generated deterministic index of all requirements.\n"
        "# Sole retrieval surface for tooling. See:\n"
        "#   openspec/architecture/decisions/ADR-0004-spec-storage-discipline.md §6\n"
        "#\n"
        "# Regenerated by `python -m tools.spec_lint index`.\n"
        "# Hand-editing is forbidden after PHASE-1; `index --check` enforces it\n"
        "# (CHG-0014 implementation; CI gate lands separately as `index-up-to-date`).\n"
        "\n"
    )
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
    return header + body


def write_index(
    specs_root: pathlib.Path,
    repo_root: pathlib.Path,
    target: pathlib.Path,
) -> None:
    data = build_index_data(specs_root, repo_root)
    target.write_text(_serialize(data))


def check_index(
    specs_root: pathlib.Path,
    repo_root: pathlib.Path,
    target: pathlib.Path,
) -> int:
    if not target.exists():
        return 2

    try:
        actual = yaml.safe_load(target.read_text())
    except yaml.YAMLError:
        return 2

    if not isinstance(actual, dict):
        return 2

    expected = build_index_data(specs_root, repo_root)

    actual_cmp = {k: v for k, v in actual.items() if k != "generated_at"}
    expected_cmp = {k: v for k, v in expected.items() if k != "generated_at"}

    return 0 if actual_cmp == expected_cmp else 1
